"""
Django settings for studifyfinal project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import dj_database_url
from dotenv import load_dotenv
import json
from google.oauth2 import service_account
import os
import base64
import logging
import firebase_admin
from firebase_admin import credentials
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.integrations.redis import RedisIntegration



logger = logging.getLogger(__name__)


load_dotenv()

sentry_sdk.logger.info('This is an info log message')
sentry_sdk.logger.warning('This is a warning message')
sentry_sdk.logger.error('This is an error message')


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'studify-production.up.railway.app', 'www.teamstudico.com', 'teamstudico.com', 'studify2-development.up.railway.app']

CSRF_TRUSTED_ORIGINS = ['https://studify-production.up.railway.app', 'https://www.teamstudico.com', 'https://teamstudico.com', 'https://studify2-development.up.railway.app']


# Base URL used for public links (e.g. referral_link)
# Default to http://www.teamstudico.com if not provided.
APP_BASE_URL = os.getenv('APP_BASE_URL', 'http://www.teamstudico.com')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.postgres',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'axes',
    'Users',
    'rest_framework',
    'channels',
    'storages',
]

ASGI_APPLICATION = 'studifyfinal.asgi.application'

# GS_BUCKET_NAME = os.getenv('GS_BUCKET_NAME')
# GS_PROJECT_ID = os.getenv('GS_PROJECT_ID')

_gcs_bucket_name = os.getenv('GS_BUCKET_NAME')
_gcs_project_id = os.getenv('GS_PROJECT_ID')
_gcs_key_env_var = os.getenv("GCS_KEY")

_gcs_credentials = None
if _gcs_key_env_var:
    try:
        _gcs_key_json = json.loads(_gcs_key_env_var)
        _gcs_credentials = service_account.Credentials.from_service_account_info(_gcs_key_json)
        logger.info("GCS_CREDENTIALS successfully created from service account info (settings.py).")
    except json.JSONDecodeError as e:
        logger.critical(f"CRITICAL ERROR: GCS_KEY JSON parsing failed in settings: {e}. GCS storage will likely fail.")
    except Exception as e:
        logger.critical(f"CRITICAL ERROR: Failed to create GCS_CREDENTIALS object in settings: {e}. GCS storage will likely fail.")
else:
    logger.critical("CRITICAL ERROR: GCS_KEY environment variable not set. GCS_CREDENTIALS will be None, GCS storage will likely fail.")


# --- NEW AND CORRECTED STORAGES CONFIGURATION (Django >= 4.2) ---
# This dictionary completely replaces DEFAULT_FILE_STORAGE and STATICFILES_STORAGE definitions.
# User uploads are private: bucket uses Uniform bucket-level access (IAM only).
# Do NOT set default_acl — GCS rejects per-object ACLs when uniform access is enabled.
# .url returns signed (expiring) URLs so only API consumers with fresh tokens can view.
STORAGES = {
    "default": { # This configures DEFAULT_FILE_STORAGE
        "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        "OPTIONS": {
            "bucket_name": _gcs_bucket_name,
            "project_id": _gcs_project_id,
            "credentials": _gcs_credentials, # Pass the created credentials object
            "file_overwrite": False,       # Matches your GS_FILE_OVERWRITE
            "default_acl": None,          # Required for Uniform bucket-level access (no per-object ACLs)
            "querystring_auth": True,      # .url returns signed (expiring) URLs
            "location": "media",           # Subdirectory in bucket for media files
            "expiration": timedelta(seconds=3600),  # Signed URLs valid for 1 hour
        },
    },
    "staticfiles": { # This configures STATICFILES_STORAGE
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


firebasecred = os.getenv("FSA")
FIREBASE_CREDENTIALS_INFO = None

if firebasecred:
    try:
        FIREBASE_CREDENTIALS_INFO = json.loads(firebasecred)
        logger.info("Firebase credentials loaded successfully from FSA environment variable.")
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse FSA environment variable as JSON: {e}. Firebase notifications will be disabled.")
    except Exception as e:
        logger.error(f"Unexpected error parsing FSA environment variable: {e}. Firebase notifications will be disabled.")
else:
    logger.warning("FSA environment variable is not set; Firebase notifications will be disabled.")

try:
    firebase_admin.get_app()
except ValueError:
    if FIREBASE_CREDENTIALS_INFO:
        try:
            cred = credentials.Certificate(FIREBASE_CREDENTIALS_INFO)
            app = firebase_admin.initialize_app(cred)
            logger.info(f"Firebase admin initialized successfully with project: {app.project_id}")
        except Exception as e:
            logger.error(f"Failed to initialize Firebase admin: {e}", exc_info=True)






sentry_sdk.init(
    dsn=os.getenv('dsn'),
    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
    send_default_pii=True,
    integrations=[
        DjangoIntegration(
            transaction_style="url",
            middleware_spans=True,
            signals_spans=True,
            cache_spans=True,
        ),
        RedisIntegration(),
    ],
    # Set traces_sample_rate to 0.1 to capture 10% of transactions for performance monitoring.
    # Reduced from 1.0 to reduce memory usage - 10% sampling is sufficient for production monitoring.
    traces_sample_rate=0.1,
    # Set profiles_sample_rate to 0.1 to profile 10% of sampled transactions.
    # Reduced from 1.0 to reduce memory usage - profiling 100% of transactions can consume 1-2GB+ of memory.
    profiles_sample_rate=0.1,
    enable_logs=True,

)





CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv('REDIS_URL')],
            "capacity": 1000,  # Increase capacity
            "expiry": 300, # Increase expiry time
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'studifyfinal.admin_security.AdminOTPRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'studifyfinal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'studifyfinal.wsgi.application'



EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.ionos.co.uk'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')  # Default to EMAIL_HOST_USER or fallback


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

POSTGRES_LOCALLY = True

if POSTGRES_LOCALLY:
    db_config = dj_database_url.parse(os.getenv('DATABASE_URL'))
    # Enable connection reuse (connection pooling)
    # CONN_MAX_AGE: Keep connections alive for 600 seconds (10 minutes)
    # This prevents opening too many new connections and reuses existing ones
    db_config['CONN_MAX_AGE'] = 0
    # Merge with existing OPTIONS if any
    if 'OPTIONS' not in db_config:
        db_config['OPTIONS'] = {}
    db_config['OPTIONS'].update({
    'connect_timeout': 10,  # ✅ Keep this
})
    DATABASES['default'] = db_config


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv('REDIS_URL'), 
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Celery Configuration
CELERY_BROKER_URL = os.getenv('REDIS_URL')  # Use Redis as message broker
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL')  # Use Redis for storing results
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# settings.py
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose', # Ensure 'verbose' formatter exists
        },
    },
    'formatters': { # Add this if you don't have it
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'loggers': {
        'storages.backends.gcloud': {
            'level': 'DEBUG', # VERY IMPORTANT
            'handlers': ['console'],
            'propagate': False,
        },
        'google.cloud.storage': { # VERY IMPORTANT
            'level': 'DEBUG',
            'handlers': ['console'],
            'propagate': False,
        },
    },
    'root': { # Catches everything else
        'handlers': ['console'],
        'level': 'DEBUG', # VERY IMPORTANT
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'GMT'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Kinde Configuration
KINDE_DOMAIN = os.getenv('KINDE_DOMAIN')
KINDE_CLIENT_ID = os.getenv('KINDE_CLIENT_ID')
KINDE_ISSUER_URL = os.getenv('KINDE_ISSUER_URL')
KINDE_USERINFO_URL = os.getenv('KINDE_USERINFO_URL')

# --- Admin panel: rate limiting (django-axes) ---
# Restrict lockout to admin login only
AXES_ONLY_ADMIN_SITE = True
AXES_FAILURE_LIMIT = 3
AXES_COOLOFF_TIME = 10  # hours
AXES_LOCK_OUT_URL = '/niagarafalls/8ball/lockout/'
AXES_IPWARE_META_PRECEDENCE_ORDER = ['HTTP_X_FORWARDED_FOR', 'REMOTE_ADDR']

# --- Admin panel: 2FA (django-otp) ---
# Admin OTP is enforced by AdminOTPRequiredMiddleware; no global OTP middleware
ADMIN_OTP_SESSION_KEY = 'admin_otp_verified'
ADMIN_URL_PREFIX = '/niagarafalls/8ball'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]