from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('',views.welcome_user),
    path('terms-of-service/', views.terms_of_service),
    path('privacy-policy/', views.privacy_policy),
    path('delete-account/', views.delete_account),
    path('open/', views.open_app),
    path('download/', views.smart_download, name='download'),
    path('get/', views.smart_download, name='get_app'),
    path('app/', views.smart_download, name='app'),
    path('qr/', views.generate_qr_code, name='qr_code'),
    path('robots.txt', views.robots_txt),
    #tested
    path('create_community/', views.create_community),
    #tested
    path('join_community/', views.join_community),
    #tested
    path('create_post/', views.create_post),
    path('like_post/', views.toggle_like_post),
    path('comment_on_post/', views.comment_on_post),
    path('comment_on_community_post/', views.comment_on_community_post),
    #tested
    path('create_community_post/', views.create_community_post),

    path('like_community_post/', views.toggle_like_community_post),

    #tested
    path('post_student_event/', views.post_student_event),
    #tested
    path('create_student/', views.create_student),
    path('edit_profile/', views.edit_profile),
    path('set_username/', views.set_username),
    path('edit_community_profile/', views.edit_community_profile),

    path('get_post_comments/', views.get_post_comments),
    path('get_community_post_comments/', views.get_community_post_comments),
    path('get_communities_of_student/', views.get_communities_of_student),
    path('get_friends_of_student/', views.get_friends_of_student),
    path('get_community_info/', views.get_community_info),
    path('get_student_info/', views.get_student_info),
    path('eventsfeed/', views.eventsfeed),
    path('postsfeed/', views.post_feed),
    path('post_community_event/', views.create_community_event),
    path('post_student_eventv1/', views.post_student_event),
    path('post_student_event_discussion/', views.post_student_events_discussion),
    path('post_community_event_discussion/', views.post_community_events_discussion),
    # delete endpoints
    path('delete_post/', views.delete_post),
    path('delete_community_post/', views.delete_community_post),
    path('delete_community_event/', views.delete_community_event),
    path('delete_student_event/', views.delete_student_event),
    path('delete_post_comment/', views.delete_post_comment),
    path('delete_community_post_comment/', views.delete_community_post_comment),
    path('delete_student_event_discussion/', views.delete_student_event_discussion),
    path('delete_community_event_discussion/', views.delete_community_event_discussion),
    path('get_student_events/', views.get_student_events),
    path('get_community_events/', views.get_community_events),
    path('get_student_posts/', views.get_student_posts),
    path('get_community_posts/', views.get_community_posts),
    path('student_event_notifs/', views.get_student_events_notifications),
    path('community_event_notifs/', views.get_community_events_notifications),
    path('friend_request_notifs/', views.get_friend_request_notifications),
    path('sfy_notifications/', views.get_sfy_notifications),
    path('other-notifications/', views.get_other_notifications),
    path('post_notifications/', views.get_post_notifications),
    path('community_notifications/', views.get_community_notifications),
    path('get_community_events_comments/', views.get_community_events_discussion),
    path('get_student_events_comments/', views.get_student_events_discussion),
    path('authuser', views.authenticate_user),   # no slash: avoid 301 redirect so clients keep Authorization header
    path('authuser/', views.authenticate_user),
    path('getotp/', views.request_student_email_verification),
    path('verifyotp/', views.verify_student_email_otp),
    path('checkifverified/', views.check_verification_status),
    path('referral/me/', views.referral_me),
    path('referral/validate/', views.referral_validate),
    path('referral/submit/', views.referral_submit),
    path('raffle/status/', views.raffle_status),
    path('raffle/draw/', views.raffle_draw),
    path('search/', views.global_search),
    path('friendsandcommunitysearch/', views.search_friends_and_communities),
    path('checkiffriend/', views.checkfriendshipstatus),
    path('getcommunityevent/', views.get_community_event),
    path('getstudentevent/', views.get_student_event),
    path('togglersvpevent/', views.toggle_rsvp_event),
    path('togglersvpcommunityevent/', views.toggle_rsvp_community_event),
    path('studentbookmarkedevents/', views.get_student_bookmarked_events),
    path('studentbookmarkedposts/', views.get_student_bookmarked_posts),
    path('togglebookmarkpost/', views.toggle_bookmark_post),
    path('togglebookmarkcommunitypost/', views.toggle_bookmark_community_post),
    path('togglebookmarkcommunityevent/', views.toggle_bookmark_community_event),
    path('togglebookmarkstudentevent/', views.toggle_bookmark_student_event),
    path('eventrsvpcount/', views.eventrsvpcount),
    path('communityeventrsvpcount/', views.communityeventrsvpcount),
    path('toggleblockstudent/', views.toggle_block_student),
    path('checkifmember/', views.checkifmembershipexists),
    path('leavecommunity/', views.leave_community),
    path('userlikes/', views.get_user_likes),
    path('userrsvps/', views.get_user_rsvps),
    path('blocked-users/', views.get_blocked_users),
    path('muted-users/', views.get_muted_users),
    path('sendimageviamessage/', views.upload_chat_image),
    path('chat/mark_messages_as_read/', views.mark_messages_as_read, name='mark-messages-as-read'),
    path('chat/direct/<str:other_user_kinde_id>/messages/', views.get_direct_messages_history, name='get-direct-messages-history'),
    path('chat/community/<int:community_id>/messages/', views.get_community_messages_history, name='get-community-chat-messages'),
    path('chat/conversations/unified/', views.get_all_unified_chats, name='get-all-unified-chats'),
    # Group chat endpoints
    path('chat/group_chats/', views.list_group_chats, name='list-group-chats'),
    path('chat/group_chats/create/', views.create_group_chat, name='create-group-chat'),
    path('chat/group_chats/<int:group_id>/', views.get_group_chat, name='get-group-chat'),
    path('chat/group_chats/<int:group_id>/update/', views.update_group_chat, name='update-group-chat'),
    path('chat/group_chats/<int:group_id>/members/add/', views.add_group_members, name='add-group-members'),
    path('chat/group_chats/<int:group_id>/members/remove/', views.remove_group_members, name='remove-group-members'),
    path('chat/group_chats/<int:group_id>/leave/', views.leave_group_chat, name='leave-group-chat'),
    path('chat/group_chats/<int:group_id>/delete/', views.delete_group_chat, name='delete-group-chat'),
    path('chat/group_chats/<int:group_id>/messages/', views.group_chat_messages, name='group-chat-messages'),
    #end
    
    path('test-upload-storage/', views.test_upload_storage, name='test-upload-storage'),
    path('test-email/', views.test_email, name='test-email'),
    path('search_chatlist/', views.search_chatlist, name='search-chatlist'),
    path('communitiesofstudentwhereadmin/', views.get_community_of_students_where_admin),
    path('save-device-token/', views.save_device_token),
    path('notify-test/', views.notify_user),
    path('radar/', views.radar),
    path('togglefriendship/', views.toggle_friend_request),
    path('get_pending_friend_requests/', views.get_pending_friend_requests),
    path('accept_friend_request/', views.accept_friendship_request),
    path('ignore_friend_request/', views.ignore_friendship_request),
    path('decline_friend_request/', views.decline_friendship_request),
    path('get_all_interests/', views.get_all_interests),
    path('get_all_regions/', views.get_all_regions),
    path('get_all_courses/', views.get_all_courses),
    path('get_all_countries/', views.get_all_countries),
    path('get_all_universities/', views.get_all_universities),
    path('get_all_locations/', views.get_all_locations),
    path('toggle_block_student/', views.toggle_block_student),
    path('toggle_community_blocks_user/', views.toggle_community_blocks_user),
    path('create_report/', views.create_report),
    path('toggle_mute_student/', views.toggle_mute_student),
    path('toggle_mute_community/', views.toggle_mute_community),
    path('send_sharable/', views.send_sharable),
    path('get_friends_in_community/', views.get_friends_in_community),
    path('get_community_members/', views.get_community_members),
    # Community admin management
    path('transfer_community_admin/', views.transfer_community_admin),
    path('promote_to_secondary_admin/', views.promote_to_secondary_admin),
    path('demote_secondary_admin/', views.demote_secondary_admin),
    path('get_post/', views.get_post),
    path('get_community_post/', views.get_community_post),
    path('get_mutual_friends/', views.get_mutual_friends),
    # Views to get people who liked or RSVPed to posts and events
    path('get_post_likes/', views.get_post_likes),
    path('get_community_post_likes/', views.get_community_post_likes),
    path('get_student_event_rsvps/', views.get_student_event_rsvps),
    path('get_community_event_rsvps/', views.get_community_event_rsvps),
    path('get_suggestions/', views.get_suggestions),
    path('request_data_deletion/', views.request_data_deletion),



    path('poster_a5_flyer/', views.poster_a5_flyer),
    path('student-ads/', views.student_ads_page),
    path('posters/', views.studico_posters),
    path('posters-light/', views.studico_posters_light),
         
]